const cards = [
  {
    "id": 1,
    "name": "SHOTGUN BABY UNICORN",
    "type": "Baby Unicorn",
    "description": "If this card would be sacrificed, destroyed, or returned to your hand, return it to the Nursery instead.",
    "color": "Magenta",
    "url": "images/1.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 2,
    "name": "BYE BYE BABY UNICORN",
    "type": "Baby Unicorn",
    "description": "If this card would be sacrificed, destroyed, or returned to your hand, return it to the Nursery instead.",
    "color": "Magenta",
    "url": "images/2.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 3,
    "name": "DUMPSTER BABY UNICORN",
    "type": "Baby Unicorn",
    "description": "If this card would be sacrificed, destroyed, or returned to your hand, return it to the Nursery instead.",
    "color": "Magenta",
    "url": "images/3.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 4,
    "name": "FUCKING CUTE BABY UNICORN",
    "type": "Baby Unicorn",
    "description": "If this card would be sacrificed, destroyed, or returned to your hand, return it to the Nursery instead.",
    "color": "Magenta",
    "url": "images/4.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 5,
    "name": "SOMEONE ELSE'S BABY UNICORN",
    "type": "Baby Unicorn",
    "description": "If this card would be sacrificed, destroyed, or returned to your hand, return it to the Nursery instead.",
    "color": "Magenta",
    "url": "images/5.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 6,
    "name": "TASTY BABY UNICORN",
    "type": "Baby Unicorn",
    "description": "If this card would be sacrificed, destroyed, or returned to your hand, return it to the Nursery instead.",
    "color": "Magenta",
    "url": "images/6.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 7,
    "name": "BABY UNICORN OF INCEST",
    "type": "Baby Unicorn",
    "description": "If this card would be sacrificed, destroyed, or returned to your hand, return it to the Nursery instead.",
    "color": "Magenta",
    "url": "images/7.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 8,
    "name": "CANNIBAL BABY UNICORN",
    "type": "Baby Unicorn",
    "description": "If this card would be sacrificed, destroyed, or returned to your hand, return it to the Nursery instead.",
    "color": "Magenta",
    "url": "images/8.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 9,
    "name": "FACELESS BABY UNICORN",
    "type": "Baby Unicorn",
    "description": "If this card would be sacrificed, destroyed, or returned to your hand, return it to the Nursery instead.",
    "color": "Magenta",
    "url": "images/9.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 10,
    "name": "FUCKING UGLY BABY UNICORN",
    "type": "Baby Unicorn",
    "description": "If this card would be sacrificed, destroyed, or returned to your hand, return it to the Nursery instead.",
    "color": "Magenta",
    "url": "images/10.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 11,
    "name": "UPSIDE DOWN BABY UNICORN",
    "type": "Baby Unicorn",
    "description": "If this card would be sacrificed, destroyed, or returned to your hand, return it to the Nursery instead.",
    "color": "Magenta",
    "url": "images/11.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 12,
    "name": "CONJOINED BABY UNICORNS",
    "type": "Baby Unicorn",
    "description": "If this card would be sacrificed, destroyed, or returned to your hand, return it to the Nursery instead.",
    "color": "Magenta",
    "url": "images/12.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 13,
    "name": "PAGEANT BABY UNICORN",
    "type": "Baby Unicorn",
    "description": "If this card would be sacrificed, destroyed, or returned to your hand, return it to the Nursery instead.",
    "color": "Magenta",
    "url": "images/13.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 14,
    "name": "STICKY SITUATION",
    "type": "Downgrade",
    "description": "If this card is in your Stable at the beginning of your turn, skip either your Draw phase or your Action phase.",
    "color": "Yellow",
    "url": "images/14.jpg",
    "activateAtBeginning": true,
    "upgrade": "",
    "downgrade": 0
  },
  {
    "id": 15,
    "name": "MID-SEX CHARLIE HORSE",
    "type": "Downgrade",
    "description": "Triggered effects of your Unicorn cards do not activate.",
    "color": "Yellow",
    "url": "images/15.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": 1
  },
  {
    "id": 16,
    "name": "LIMP HORN",
    "type": "Downgrade",
    "description": "You cannot play Upgrade cards.",
    "color": "Yellow",
    "url": "images/16.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": 2
  },
  {
    "id": 17,
    "name": "AUTOEROTIC ASPHYXIATION",
    "type": "Downgrade",
    "description": "If this card is in your Stable at the beginning of your turn, DISCARD a card.",
    "color": "Yellow",
    "url": "images/17.jpg",
    "activateAtBeginning": true,
    "upgrade": "",
    "downgrade": 3
  },
  {
    "id": 18,
    "name": "UNICORN FLATULENCE",
    "type": "Downgrade",
    "description": "If this card is in your Stable at the beginning of your turn, return a Unicorn card from your Stable to your hand. If at any time you have no Unicorn cards in your Stable, SACRIFICE this card.",
    "color": "Yellow",
    "url": "images/18.jpg",
    "activateAtBeginning": true,
    "upgrade": "",
    "downgrade": 4
  },
  {
    "id": 19,
    "name": "UNICORN BUTT PLUG",
    "type": "Downgrade",
    "description": "Your hand limit is 3 cards.",
    "color": "Yellow",
    "url": "images/19.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": 5
  },
  {
    "id": 20,
    "name": "HORSE SHIT",
    "type": "Downgrade",
    "description": "All of your Unicorn cards are considered Shits. Cards that affect Unicorn cards do not affect Shits.",
    "color": "Yellow",
    "url": "images/20.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": 6
  },
  {
    "id": 21,
    "name": "PUTTING ON A SHOW",
    "type": "Upgrade",
    "description": "If this card is in your Stable at the beginning of your turn, you may SACRIFICE a card. If you do, DESTROY a card.",
    "color": "Orange",
    "url": "images/21.jpg",
    "activateAtBeginning": true,
    "upgrade": 0,
    "downgrade": ""
  },
  {
    "id": 221,
    "name": "PUTTING ON A SHOW",
    "type": "Upgrade",
    "description": "If this card is in your Stable at the beginning of your turn, you may SACRIFICE a card. If you do, DESTROY a card.",
    "color": "Orange",
    "url": "images/21.jpg",
    "activateAtBeginning": true,
    "upgrade": 0,
    "downgrade": ""
  },
  {
    "id": 22,
    "name": "UNICORN DUNGEON",
    "type": "Upgrade",
    "description": "If this card is in your Stable at the beginning of your turn, you may play 2 cards during your Action phase.",
    "color": "Orange",
    "url": "images/22.jpg",
    "activateAtBeginning": true,
    "upgrade": 1,
    "downgrade": ""
  },
  {
    "id": 23,
    "name": "PONY PLAY",
    "type": "Upgrade",
    "description": "If this card is in your Stable at the beginning of your turn, you may choose any other player. Pull a card from that player's hand and add it to your hand. If you do, skip your Draw phase.",
    "color": "Orange",
    "url": "images/23.jpg",
    "activateAtBeginning": true,
    "upgrade": 2,
    "downgrade": ""
  },
  {
    "id": 223,
    "name": "PONY PLAY",
    "type": "Upgrade",
    "description": "If this card is in your Stable at the beginning of your turn, you may choose any other player. Pull a card from that player's hand and add it to your hand. If you do, skip your Draw phase.",
    "color": "Orange",
    "url": "images/23.jpg",
    "activateAtBeginning": true,
    "upgrade": 2,
    "downgrade": ""
  },
  {
    "id": 24,
    "name": "NO STRINGS ATTACHED",
    "type": "Upgrade",
    "description": "If this card is in your Stable at the beginning of your turn, you may STEAL a Unicorn card. At the end of your turn, return that Unicorn card to the Stable from which you stole it.",
    "color": "Orange",
    "url": "images/24.jpg",
    "activateAtBeginning": true,
    "upgrade": 3,
    "downgrade": ""
  },
  {
    "id": 25,
    "name": "UNICORN SPEED",
    "type": "Upgrade",
    "description": "This card can only enter a Stable if there is a Basic Unicorn card in that Stable. If this card is in your Stable at the beginning of your turn, you may DRAW an extra card.",
    "color": "Orange",
    "url": "images/25.jpg",
    "activateAtBeginning": true,
    "upgrade": 4,
    "downgrade": ""
  },
  {
    "id": 225,
    "name": "UNICORN SPEED",
    "type": "Upgrade",
    "description": "This card can only enter a Stable if there is a Basic Unicorn card in that Stable. If this card is in your Stable at the beginning of your turn, you may DRAW an extra card.",
    "color": "Orange",
    "url": "images/25.jpg",
    "activateAtBeginning": true,
    "upgrade": 4,
    "downgrade": ""
  },
  {
    "id": 26,
    "name": "DOMINATRIX WHIP",
    "type": "Upgrade",
    "description": "If this card is in your Stable at the beginning of your turn, you may move a Unicorn card from any player's Stable to any other player's Stable. You cannot move that card into your own Stable.",
    "color": "Orange",
    "url": "images/26.jpg",
    "activateAtBeginning": true,
    "upgrade": 5,
    "downgrade": ""
  },
  {
    "id": 27,
    "name": "UNICORN WITH BENEFITS",
    "type": "Upgrade",
    "description": "This card can only enter a Stable if there is a Basic Unicorn card in that Stable. If this card is in your Stable at the beginning of your turn, you may bring a Basic Unicorn card from your hand directly into your Stable.",
    "color": "Orange",
    "url": "images/27.jpg",
    "activateAtBeginning": true,
    "upgrade": 6,
    "downgrade": ""
  },
  {
    "id": 28,
    "name": "BLOW UP UNICORN",
    "type": "Upgrade",
    "description": "If 1 of your Unicorns would be sacrificed or destroyed, you may SACRIFICE this card instead.",
    "color": "Orange",
    "url": "images/28.jpg",
    "activateAtBeginning": false,
    "upgrade": 7,
    "downgrade": ""
  },
  {
    "id": 228,
    "name": "BLOW UP UNICORN",
    "type": "Upgrade",
    "description": "If 1 of your Unicorns would be sacrificed or destroyed, you may SACRIFICE this card instead.",
    "color": "Orange",
    "url": "images/28.jpg",
    "activateAtBeginning": false,
    "upgrade": 7,
    "downgrade": ""
  },
  {
    "id": 29,
    "name": "UNICORN CHASTITY BELT",
    "type": "Upgrade",
    "description": "Your Unicorn cards cannot be destroyed.",
    "color": "Orange",
    "url": "images/29.jpg",
    "activateAtBeginning": false,
    "upgrade": 8,
    "downgrade": ""
  },
  {
    "id": 30,
    "name": "UNICORN VIBRATOR",
    "type": "Upgrade",
    "description": "If this card is in your Stable at the beginning of your turn, you may DRAW a card at the end of your turn.",
    "color": "Orange",
    "url": "images/30.jpg",
    "activateAtBeginning": true,
    "upgrade": 9,
    "downgrade": ""
  },
  {
    "id": 230,
    "name": "UNICORN VIBRATOR",
    "type": "Upgrade",
    "description": "If this card is in your Stable at the beginning of your turn, you may DRAW a card at the end of your turn.",
    "color": "Orange",
    "url": "images/30.jpg",
    "activateAtBeginning": true,
    "upgrade": 9,
    "downgrade": ""
  },
  {
    "id": 31,
    "name": "HORSE WITH A DILDO",
    "type": "Basic Unicorn",
    "description": "Sometimes a horse just needs to feel a little special.",
    "color": "Purple",
    "url": "images/31.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 231,
    "name": "HORSE WITH A DILDO",
    "type": "Basic Unicorn",
    "description": "Sometimes a horse just needs to feel a little special.",
    "color": "Purple",
    "url": "images/31.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 331,
    "name": "HORSE WITH A DILDO",
    "type": "Basic Unicorn",
    "description": "Sometimes a horse just needs to feel a little special.",
    "color": "Purple",
    "url": "images/31.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 32,
    "name": "WASTED WHITE UNICORN",
    "type": "Basic Unicorn",
    "description": "#livingfortheweekend",
    "color": "Purple",
    "url": "images/32.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 232,
    "name": "WASTED WHITE UNICORN",
    "type": "Basic Unicorn",
    "description": "#livingfortheweekend",
    "color": "Purple",
    "url": "images/32.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 332,
    "name": "WASTED WHITE UNICORN",
    "type": "Basic Unicorn",
    "description": "#livingfortheweekend",
    "color": "Purple",
    "url": "images/32.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 33,
    "name": "UNICORN ON THE STREET CORNER",
    "type": "Basic Unicorn",
    "description": "I'm expensive, but I'm worth it.",
    "color": "Purple",
    "url": "images/33.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 233,
    "name": "UNICORN ON THE STREET CORNER",
    "type": "Basic Unicorn",
    "description": "I'm expensive, but I'm worth it.",
    "color": "Purple",
    "url": "images/33.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 333,
    "name": "UNICORN ON THE STREET CORNER",
    "type": "Basic Unicorn",
    "description": "I'm expensive, but I'm worth it.",
    "color": "Purple",
    "url": "images/33.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 34,
    "name": "VANILLACORN",
    "type": "Basic Unicorn",
    "description": "My body is ready!",
    "color": "Purple",
    "url": "images/34.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 234,
    "name": "VANILLACORN",
    "type": "Basic Unicorn",
    "description": "My body is ready!",
    "color": "Purple",
    "url": "images/34.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 334,
    "name": "VANILLACORN",
    "type": "Basic Unicorn",
    "description": "My body is ready!",
    "color": "Purple",
    "url": "images/34.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 35,
    "name": "FUCKBOI UNICORN",
    "type": "Basic Unicorn",
    "description": "send pics 👊🏼🍆💦💦",
    "color": "Purple",
    "url": "images/35.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 235,
    "name": "FUCKBOI UNICORN",
    "type": "Basic Unicorn",
    "description": "send pics 👊🏼🍆💦💦",
    "color": "Purple",
    "url": "images/35.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 335,
    "name": "FUCKBOI UNICORN",
    "type": "Basic Unicorn",
    "description": "send pics 👊🏼🍆💦💦",
    "color": "Purple",
    "url": "images/35.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 36,
    "name": "STONER UNICORN",
    "type": "Basic Unicorn",
    "description": "It's 4:20 somewhere.",
    "color": "Purple",
    "url": "images/36.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 236,
    "name": "STONER UNICORN",
    "type": "Basic Unicorn",
    "description": "It's 4:20 somewhere.",
    "color": "Purple",
    "url": "images/36.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 336,
    "name": "STONER UNICORN",
    "type": "Basic Unicorn",
    "description": "It's 4:20 somewhere.",
    "color": "Purple",
    "url": "images/36.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 37,
    "name": "SINGLE UNICORN",
    "type": "Basic Unicorn",
    "description": "The single life.",
    "color": "Purple",
    "url": "images/37.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 237,
    "name": "SINGLE UNICORN",
    "type": "Basic Unicorn",
    "description": "The single life.",
    "color": "Purple",
    "url": "images/37.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 337,
    "name": "SINGLE UNICORN",
    "type": "Basic Unicorn",
    "description": "The single life.",
    "color": "Purple",
    "url": "images/37.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 38,
    "name": "DOUBLE AGENT UNICORN",
    "type": "Magical Unicorn",
    "description": "If this card is in your Stable at the beginning of your turn, you may SACRIFICE a Basic Unicorn card. If you do, pull a card from each other player's hand and add it to your hand.",
    "color": "Blue",
    "url": "images/38.jpg",
    "activateAtBeginning": true,
    "upgrade": 10,
    "downgrade": ""
  },
  {
    "id": 39,
    "name": "KITTENCORN IN HEAT",
    "type": "Magical Unicorn",
    "description": "If this card is in your Stable at the beginning of your turn, you may DISCARD a card. If you do, bring a Baby Unicorn card from the Nursery directly into your Stable.",
    "color": "Blue",
    "url": "images/39.jpg",
    "activateAtBeginning": true,
    "upgrade": 11,
    "downgrade": ""
  },
  {
    "id": 40,
    "name": "SADOMASOCORN",
    "type": "Magical Unicorn",
    "description": "If this card is in your Stable at the beginning of your turn, you may SACRIFICE a card. If you do, DESTROY a card.",
    "color": "Blue",
    "url": "images/40.jpg",
    "activateAtBeginning": true,
    "upgrade": "",
    "downgrade": 9
  },
  {
    "id": 41,
    "name": "FLESH-EATING UNICORN",
    "type": "Magical Unicorn",
    "description": "When this card enters your Stable, you may choose any player. That player must DISCARD 2 cards.",
    "color": "Blue",
    "url": "images/41.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": 10
  },
  {
    "id": 42,
    "name": "GIANT HORNED COCK",
    "type": "Magical Unicorn",
    "description": "This card counts for 2 Unicorns. You cannot play Magic cards.",
    "color": "Blue",
    "url": "images/42.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": 11
  },
  {
    "id": 43,
    "name": "STRAIGHT BUT CURIOUS UNICORN",
    "type": "Magical Unicorn",
    "description": "When this card enters your Stable, you may look at the top 3 cards of the deck, then return them in the same order.",
    "color": "Blue",
    "url": "images/43.jpg",
    "activateAtBeginning": false,
    "upgrade": 12,
    "downgrade": ""
  },
  {
    "id": 44,
    "name": "TWINKICORN",
    "type": "Magical Unicorn",
    "description": "When this card enters your Stable, you may search the deck for a \"Bear Daddy Unicorn\" card. Add it to your hand, then shuffle the deck.",
    "color": "Blue",
    "url": "images/44.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 45,
    "name": "DUMPSTER DIVING UNICORN",
    "type": "Magical Unicorn",
    "description": "When this card enters your Stable, you may choose a card from the discard pile and add it to your hand.",
    "color": "Blue",
    "url": "images/45.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 46,
    "name": "HENTAICORN",
    "type": "Magical Unicorn",
    "description": "If 1 of your Unicorn cards would be destroyed, you may SACRIFICE this card instead.",
    "color": "Blue",
    "url": "images/46.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 47,
    "name": "HOMICIDAL PSYCHOCORN",
    "type": "Magical Unicorn",
    "description": "If this card is in your Stable at the beginning of your turn, you may DISCARD your hand. If you do, DESTROY a Unicorn card.",
    "color": "Blue",
    "url": "images/47.jpg",
    "activateAtBeginning": true,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 48,
    "name": "UNCUT UNICORN",
    "type": "Magical Unicorn",
    "description": "Your hand limit increases by 1.",
    "color": "Blue",
    "url": "images/48.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 49,
    "name": "UNICORN CUCKOLD",
    "type": "Magical Unicorn",
    "description": "If this card is in your Stable at the beginning of your turn, move a Unicorn card from your Stable into any other player's Stable. At the end of your turn, return that Unicorn card to your Stable.",
    "color": "Blue",
    "url": "images/49.jpg",
    "activateAtBeginning": true,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 50,
    "name": "BEAR DADDY UNICORN",
    "type": "Magical Unicorn",
    "description": "When this card enters your Stable, you may search the deck for a \"Twinkicorn\" card. Add it to your hand, then shuffle the deck.",
    "color": "Blue",
    "url": "images/50.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 51,
    "name": "MOTHER FUCKIN' FLYING UNICORN",
    "type": "Magical Unicorn",
    "description": "When this card enters your Stable, you may choose any player. That player must DISCARD a card. If this card would be sacrificed or destroyed, return it to your hand instead.",
    "color": "Blue",
    "url": "images/51.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 52,
    "name": "POLYAMOROUS UNICORN",
    "type": "Magical Unicorn",
    "description": "If this card is in your Stable at the beginning of your turn, you may move this card to any other player's Stable. If you do, STEAL a Unicorn card from that player's Stable.",
    "color": "Blue",
    "url": "images/52.jpg",
    "activateAtBeginning": true,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 53,
    "name": "UNEXPECTED MIRACLE UNICORN",
    "type": "Magical Unicorn",
    "description": "When this card enters your Stable, you may DISCARD a card from the Nursery directly into your Stable.",
    "color": "Blue",
    "url": "images/53.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 54,
    "name": "SEXTRA-TERRESTRIAL UNICORN",
    "type": "Magical Unicorn",
    "description": "When this card enters your Stable, you may return a card in any player's Stable to that player's hand.",
    "color": "Blue",
    "url": "images/54.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 55,
    "name": "ENTITLED UNICORN",
    "type": "Magical Unicorn",
    "description": "When this card enters your Stable, you may choose any other player and look at that player's hand. Choose a Unicorn card from that player's hand and add it to your hand.",
    "color": "Blue",
    "url": "images/55.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 56,
    "name": "NAKED NARWHAL",
    "type": "Magical Unicorn",
    "description": "When this card enters your Stable, STEAL a Basic Unicorn card. If this card leaves your Stable, return that Basic Unicorn card to the Stable from which you stole it.",
    "color": "Blue",
    "url": "images/56.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 57,
    "name": "EUNUCHORN",
    "type": "Magical Unicorn",
    "description": "Baby Unicorn cards cannot enter any player's Stable.",
    "color": "Blue",
    "url": "images/57.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 58,
    "name": "HORNY FLYING UNICORN",
    "type": "Magical Unicorn",
    "description": "When this card enters your Stable, STEAL a Unicorn card. At the end of your turn, return that Unicorn card to the Stable from which you stole it. If this card would be sacrificed or destroyed, return it to your hand instead.",
    "color": "Blue",
    "url": "images/58.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 59,
    "name": "OFFICER HORNIE",
    "type": "Magical Unicorn",
    "description": "When this card enters your Stable, choose a player and look at their hand. Choose a Unicorn card in that player's hand and move it to the discard pile.",
    "color": "Blue",
    "url": "images/59.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 60,
    "name": "CULT LEADER UNICORN",
    "type": "Magical Unicorn",
    "description": "When this card enters your Stable, each player must SACRIFICE a Unicorn card.",
    "color": "Blue",
    "url": "images/60.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 61,
    "name": "BUKKAKECORN",
    "type": "Magical Unicorn",
    "description": "If this card is in your Stable at the beginning of your turn, you may STEAL a Unicorn card. At the end of your turn, return that Unicorn card to the Stable from which you stole it.",
    "color": "Blue",
    "url": "images/61.jpg",
    "activateAtBeginning": true,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 62,
    "name": "MOIST UNICORN",
    "type": "Magical Unicorn",
    "description": "When this card enters your Stable, you may search the deck for a Unicorn card and add it to your hand. Shuffle the deck.",
    "color": "Blue",
    "url": "images/62.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 63,
    "name": "UNICORN DANCER",
    "type": "Magical Unicorn",
    "description": "If this card is in your Stable at the beginning of your turn, you may DRAW an extra card, then DISCARD a card.",
    "color": "Blue",
    "url": "images/63.jpg",
    "activateAtBeginning": true,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 64,
    "name": "SEMENBISCUIT",
    "type": "Magical Unicorn",
    "description": "When this card enters your Stable, SACRIFICE all Downgrade cards.",
    "color": "Blue",
    "url": "images/64.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 65,
    "name": "TOTAL STUD UNICORN",
    "type": "Magical Unicorn",
    "description": "This card counts for 2 Unicorns. You cannot play Basic Unicorn cards.",
    "color": "Blue",
    "url": "images/65.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 66,
    "name": "FREE CANDY UNICORN",
    "type": "Magical Unicorn",
    "description": "When this card enters your Stable, STEAL a Baby Unicorn card. If this card leaves your Stable, return that Baby Unicorn card to the Stable from which you stole it.",
    "color": "Blue",
    "url": "images/66.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 67,
    "name": "MANSCAPED LLAMACORN",
    "type": "Magical Unicorn",
    "description": "When this card enters your Stable, each other player must DISCARD a card.",
    "color": "Blue",
    "url": "images/67.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 68,
    "name": "THE BITCHIEST UNICORN",
    "type": "Magical Unicorn",
    "description": "This card can only enter a Stable if there is a Basic Unicorn card in that Stable. If this card is in your Stable at the beginning of your turn, you may choose any player. That player must DISCARD a card.",
    "color": "Blue",
    "url": "images/68.jpg",
    "activateAtBeginning": true,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 69,
    "name": "RAINBOW SHITSTORM",
    "type": "Magic",
    "description": "Each player must SACRIFICE a card and DISCARD their hand. Shuffle the discard pile into the deck. Deal 5 cards to each player.",
    "color": "Green",
    "url": "images/69.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 70,
    "name": "UNICORN HANGOVER",
    "type": "Magic",
    "description": "Choose any player. That player must skip their next turn.",
    "color": "Green",
    "url": "images/70.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 71,
    "name": "SEX, DRUGS, AND UNICORNS",
    "type": "Magic",
    "description": "Choose a player. That player must DISCARD 3 cards or SACRIFICE a Unicorn card.",
    "color": "Green",
    "url": "images/71.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 72,
    "name": "BREAKING AND ENTERING",
    "type": "Magic",
    "description": "Choose any other player. Pull 2 cards from that player's hand and add them to your hand.",
    "color": "Green",
    "url": "images/72.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 272,
    "name": "BREAKING AND ENTERING",
    "type": "Magic",
    "description": "Choose any other player. Pull 2 cards from that player's hand and add them to your hand.",
    "color": "Green",
    "url": "images/72.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 73,
    "name": "BABY TRAP",
    "type": "Magic",
    "description": "STEAL a Baby Unicorn card.",
    "color": "Green",
    "url": "images/73.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 273,
    "name": "BABY TRAP",
    "type": "Magic",
    "description": "STEAL a Baby Unicorn card.",
    "color": "Green",
    "url": "images/73.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 74,
    "name": "MAKE IT RAIN",
    "type": "Magic",
    "description": "DISCARD 2 cards, then DRAW 2 cards. Take another turn.",
    "color": "Green",
    "url": "images/74.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 75,
    "name": "FUCK, MARRY, KILL.",
    "type": "Magic",
    "description": "Choose any player. That player must DISCARD a card. Give any player a card from your hand, then DESTROY a Unicorn card.",
    "color": "Green",
    "url": "images/75.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 275,
    "name": "FUCK, MARRY, KILL.",
    "type": "Magic",
    "description": "Choose any player. That player must DISCARD a card. Give any player a card from your hand, then DESTROY a Unicorn card.",
    "color": "Green",
    "url": "images/75.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 76,
    "name": "UNICORN ENEMA",
    "type": "Magic",
    "description": "SACRIFICE or DESTROY all Downgrade cards in any player's Stable.",
    "color": "Green",
    "url": "images/76.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 77,
    "name": "KINK SHAME",
    "type": "Magic",
    "description": "SACRIFICE or DESTROY an Upgrade or Downgrade card.",
    "color": "Green",
    "url": "images/77.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 277,
    "name": "KINK SHAME",
    "type": "Magic",
    "description": "SACRIFICE or DESTROY an Upgrade or Downgrade card.",
    "color": "Green",
    "url": "images/77.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 377,
    "name": "KINK SHAME",
    "type": "Magic",
    "description": "SACRIFICE or DESTROY an Upgrade or Downgrade card.",
    "color": "Green",
    "url": "images/77.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 78,
    "name": "BLAZE AND GRAZE",
    "type": "Magic",
    "description": "Reveal the top card in the deck. If it is a Unicorn card, bring it directly into your Stable and take another turn. If it is a Downgrade card, DISCARD it and SACRIFICE a Unicorn card. If it is anything else, add it to your hand.",
    "color": "Green",
    "url": "images/78.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 79,
    "name": "SAFE SEX",
    "type": "Magic",
    "description": "Each player must return a Baby Unicorn card from their Stable to the Nursery.",
    "color": "Green",
    "url": "images/79.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 80,
    "name": "UNICORN ACID TRIP",
    "type": "Magic",
    "description": "Each player must DISCARD their hand and DRAW the same number of cards. DRAW 2 additional cards.",
    "color": "Green",
    "url": "images/80.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 81,
    "name": "HORRIFYING IMPALING",
    "type": "Magic",
    "description": "DESTROY a Unicorn card. Each player must DISCARD a card.",
    "color": "Green",
    "url": "images/81.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 281,
    "name": "HORRIFYING IMPALING",
    "type": "Magic",
    "description": "DESTROY a Unicorn card. Each player must DISCARD a card.",
    "color": "Green",
    "url": "images/81.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 82,
    "name": "MAKE IT SNOW",
    "type": "Magic",
    "description": "DISCARD your hand, then DRAW 3 cards. Take another turn.",
    "color": "Green",
    "url": "images/82.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 83,
    "name": "UNICORGY",
    "type": "Magic",
    "description": "If you have more than 3 Unicorns in your Stable, DRAW cards equal to the number of Unicorns in your Stable minus 3.",
    "color": "Green",
    "url": "images/83.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 283,
    "name": "UNICORGY",
    "type": "Magic",
    "description": "If you have more than 3 Unicorns in your Stable, DRAW cards equal to the number of Unicorns in your Stable minus 3.",
    "color": "Green",
    "url": "images/83.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 84,
    "name": "HOOF JOB",
    "type": "Magic",
    "description": "Choose any player and look at that player's hand. Choose a card from that player's hand and add it to your hand.",
    "color": "Green",
    "url": "images/84.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 284,
    "name": "HOOF JOB",
    "type": "Magic",
    "description": "Choose any player and look at that player's hand. Choose a card from that player's hand and add it to your hand.",
    "color": "Green",
    "url": "images/84.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 85,
    "name": "BUCK NAKED",
    "type": "Magic",
    "description": "SACRIFICE or DESTROY all Upgrade cards in any player's Stable.",
    "color": "Green",
    "url": "images/85.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": ""
  },
  {
    "id": 86,
    "name": "NEIGH, MOTHERFUCKER",
    "type": "Instant",
    "description": "Play this card when any other player tries to play a card. Stop that player's card from being played and send it to the discard pile. That player must DISCARD a card.",
    "color": "Red",
    "url": "images/86.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": 8
  },
  {
    "id": 286,
    "name": "NEIGH, MOTHERFUCKER",
    "type": "Instant",
    "description": "Play this card when any other player tries to play a card. Stop that player's card from being played and send it to the discard pile. That player must DISCARD a card.",
    "color": "Red",
    "url": "images/86.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": 8
  },
  {
    "id": 386,
    "name": "NEIGH, MOTHERFUCKER",
    "type": "Instant",
    "description": "Play this card when any other player tries to play a card. Stop that player's card from being played and send it to the discard pile. That player must DISCARD a card.",
    "color": "Red",
    "url": "images/86.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": 8
  },
  {
    "id": 87,
    "name": "THE SAFEWORD IS NEIGH",
    "type": "Instant",
    "description": "Play this card when any other player tries to play a card. Stop that player's card from being played and send it to the discard pile.",
    "color": "Red",
    "url": "images/87.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": 7
  },
  {
    "id": 287,
    "name": "THE SAFEWORD IS NEIGH",
    "type": "Instant",
    "description": "Play this card when any other player tries to play a card. Stop that player's card from being played and send it to the discard pile.",
    "color": "Red",
    "url": "images/87.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": 7
  },
  {
    "id": 387,
    "name": "THE SAFEWORD IS NEIGH",
    "type": "Instant",
    "description": "Play this card when any other player tries to play a card. Stop that player's card from being played and send it to the discard pile.",
    "color": "Red",
    "url": "images/87.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": 7
  },
  {
    "id": 487,
    "name": "THE SAFEWORD IS NEIGH",
    "type": "Instant",
    "description": "Play this card when any other player tries to play a card. Stop that player's card from being played and send it to the discard pile.",
    "color": "Red",
    "url": "images/87.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": 7
  },
  {
    "id": 587,
    "name": "THE SAFEWORD IS NEIGH",
    "type": "Instant",
    "description": "Play this card when any other player tries to play a card. Stop that player's card from being played and send it to the discard pile.",
    "color": "Red",
    "url": "images/87.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": 7
  },
  {
    "id": 687,
    "name": "HELL NEIGH",
    "type": "Instant",
    "description": "Play this card when any other player tries to play a card. Stop that player's card from being played and send it to the discard pile.",
    "color": "Red",
    "url": "images/88.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": 7
  },
  {
    "id": 88,
    "name": "HELL NEIGH",
    "type": "Instant",
    "description": "Play this card when any other player tries to play a card. Stop that player's card from being played and send it to the discard pile.",
    "color": "Red",
    "url": "images/88.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": 7
  },
  {
    "id": 288,
    "name": "HELL NEIGH",
    "type": "Instant",
    "description": "Play this card when any other player tries to play a card. Stop that player's card from being played and send it to the discard pile.",
    "color": "Red",
    "url": "images/88.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": 7
  },
  {
    "id": 89,
    "name": "NEIGH, BITCH",
    "type": "Instant",
    "description": "Play this card when any other player tries to play a card. Stop that player's card from being played and send it to the discard pile.",
    "color": "Red",
    "url": "images/89.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": 7
  },
  {
    "id": 289,
    "name": "NEIGH, BITCH",
    "type": "Instant",
    "description": "Play this card when any other player tries to play a card. Stop that player's card from being played and send it to the discard pile.",
    "color": "Red",
    "url": "images/89.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": 7
  },
  {
    "id": 389,
    "name": "NEIGH, BITCH",
    "type": "Instant",
    "description": "Play this card when any other player tries to play a card. Stop that player's card from being played and send it to the discard pile.",
    "color": "Red",
    "url": "images/89.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": 7
  },
  {
    "id": 90,
    "name": "NEIGH MEANS NEIGH",
    "type": "Instant",
    "description": "Play this card when any other player tries to play a card. Stop that player's card from being played and send it to the discard pile. This card cannot be Neigh'd.",
    "color": "Red",
    "url": "images/90.jpg",
    "activateAtBeginning": false,
    "upgrade": "",
    "downgrade": 7
  }
];

export default cards
